.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PASM" "1" "May 2016" "" ""
.
.SH "NAME"
\fBpasm\fR \- Assembler for PRU subsystem included in OMAP\-L1x8/C674m/AM18xx devices
.
.SH "SYNOPSIS"
\fBpasm\fR [\-V#EBbcmLldfz] [\-Idir] [\-Dname=value] [\-Cname] InFile [OutFileBase]
.
.SH "DESCRIPTION"
\fBpasm\fR is a command line driven assembler for the Programmable Real\-time execution unit (PRU) of the Programmable Real\-time Unit Subsystem (PRUSS)\. It is designed to build single executable images using a flexible source code syntax and a variety of output options\. PASM is available for Windows and Linux\.
.
.SH "Calling Syntax"
The command line syntax to \fBPASM\fR is:
.
.P
\fBpasm\fR [\-bBcmldexfz] SourceFile [OutFileBasename] [\-Dname=value] [\-CArrayName]
.
.P
Note that only the source file SourceFile is required on the command line\. The assembler will default to output option "\-c" which generates a C array containing the binary opcode data\. The majority of the option flags select a variety of output formats\.
.
.P
The output file OutFileBasename is a base name only\. It defaults to the same name as the source file (for example "myprog\.p" would have a default base name of "myprog"\. Standard filename extensions are applied to the base name to create the final output filename(s), depending on the output option(s) selected\.
.
.P
When specifying PASM options, options can be specified individually or as a group\. For example, either of the two invocations below is valid:
.
.IP "" 4
.
.nf

pasm \-cdl myprog\.p
pasm \-c \-d \-l myprog\.p
.
.fi
.
.IP "" 0
.
.P
Also filenames and options can be mixed for example:
.
.IP "" 4
.
.nf

pasm myprog\.p \-cdl
pasm \-cd myprog\.p \-DMYVAL=1 \-l
.
.fi
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fB\-V#\fR
Specify core version (V0,V1,V2,V3)\. (Default is V1)
.
.TP
\fB\-E\fR
Assemble for big endian core
.
.TP
\fB\-B\fR
Create big endian binary output (*\.bib)
.
.TP
\fB\-b\fR
Create little endian binary output (*\.bin)
.
.TP
\fB\-c\fR
Create "C array" binary output (*_bin\.h)
.
.TP
\fB\-m\fR
Create "image" binary output (*\.img)
.
.TP
\fB\-L\fR
Create annotated source file style listing (*\.txt)
.
.TP
\fB\-l\fR
Create raw listing file (*\.lst)
.
.TP
\fB\-d\fR
Create pView debug file (*\.dbg)
.
.TP
\fB\-f\fR
Create "FreeBasic array" binary output (*\.bi)
.
.TP
\fB\-z\fR
Enable debug messages
.
.TP
\fB\-I\fR
Add the directory dir to search path for #include "filename" type of directives (where angled brackets are used instead of quotes)\.
.
.TP
\fB\-D\fR
Set equate "name" to 1 using "\-Dname", or to any value using "\-Dname=value"
.
.TP
\fB\-C\fR
Name the C array in "C array" binary output to "name" using "\-Cname"
.
.SH "COPYRIGHT"
\fBpasm\fR is (C) 2005\-2013 by Texas Instruments Inc\.
