

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int PRUcode[] =  {
     0xc91fff00,
     0x240000d1,
     0x24001191,
     0x81242091,
     0x240000e0,
     0x240002c1,
     0x24202c81,
     0xe1002180,
     0x24000af1,
     0x81003f91,
     0x240000ec,
     0x2400221f,
     0x2400241f,
     0x2a000000 };

